pipeline {
  agent any
  environment{
  SCANNER_HOME= tool 'sonar'
  }
  stages {
    stage('Static Code Analysis') {
      steps {
        withSonarQubeEnv('sonarqube') {
        sh '${SCANNER_HOME}/bin/sonar-scanner'
            }
        }
      }
      stage('Unit Test') {
         steps {
          echo 'Unit testing'
               }
      }
    
    stage('build') {
      steps { 
            echo 'echo3'
      }
    } 
  }
}
