pipeline {
  agent any
  stages {
    stage('SonarQube') {
      steps {
          echo 'Unit testing from github'
      }
    }
    stage('Unit Test') {
      steps {
        echo 'Unit testing'
      }
    }
    stage('build') {
      steps {
            echo "Build "
      }
    }
   
  }
}
